# Schema for the configuration files of the Event Sync module.
middlebury_event_sync.settings:
  type: config_object
  label: 'Event Sync settings'
  mapping:
    enabled:
      type: boolean
      label: 'Sync Enabled:'

middlebury_event_sync.event_source.*:
  type: config_entity
  label: 'Event Source config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    provider:
      type: string
      label: 'Provider'
    plugin:
      type: string
      label: 'Plugin'
    settings:
      type: middlebury_event_sync.event_source_plugin.[%parent.plugin]
